### ISSUE TITLE
Readme: Suggest users to try vim.g.scrolloff = 1000 before installing this plugin

### ISSUE THREAD

**Issue by Zeioth** [arnamak/stay-centered.nvim#9]
This plugin may cause interferences with other plugins like mini.animate, while the option doesn't, while achieving the same result.

It is a good idea if we put in knowledge of our users that this option exsist.

**Comment by arnamak** [comment]
Hello,

`vim.g.scrolloff = 1000` isn't the same as the functionality of this plugin. In fact, the inspiration for creating this plugin was because everybody recommends `vim.g.scrolloff`, but it doesn't _stay centered_ all the time with that setting.

The native vim equivalent to the functionality of this plugin is:
```
nnoremap "j" "jzz"
nnoremap "n" "nzzzv"
```
But that is listed in the Summary section of the README.
